DROP DATABASE IF EXISTS KIRK_KASINOA;

CREATE DATABASE KIRK_KASINOA;

USE KIRK_KASINOA;

CREATE TABLE USERS (
DNI VARCHAR(10) PRIMARY KEY,
USERNAME VARCHAR(20) NOT NULL,
PASWORD VARCHAR(10) NOT NULL,
DATE_OF_BIRTH DATE,
TIMES_PLAYED INT,
MAX_COMBO INT,
BALANCE DECIMAL CHECK (BALANCE BETWEEN 0 AND 5000)
);

CREATE TABLE TABLEE(
ID_TABLE VARCHAR(10) PRIMARY KEY,
GAME_TYPE ENUM ('BLACKJACK','ROULETTE')
);

CREATE TABLE DEALER(
ID_DEALER VARCHAR(10) PRIMARY KEY,
DEALER_NAME VARCHAR(20) NOT NULL,
BALANCE DECIMAL CHECK (BALANCE BETWEEN 0 AND 5000)
);

CREATE TABLE PLAYED(
DNI VARCHAR(10),
ID_TABLE VARCHAR(10),
GAME_DATE TIMESTAMP,
BET INT,
PRIMARY KEY(DNI,ID_TABLE,GAME_DATE),
RESULT ENUM ('WIN','LOSE','DRAW'), 
FOREIGN KEY (DNI) REFERENCES USERS(DNI) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ID_TABLE) REFERENCES TABLEE(ID_TABLE) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HAVE(
ID_TABLE VARCHAR(10),
ID_DEALER VARCHAR(10),
FOREIGN KEY(ID_TABLE) REFERENCES TABLEE(ID_TABLE) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(ID_DEALER) REFERENCES DEALER(ID_DEALER) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO USERS VALUES
('18449847Y', 'Enio', 'David43210','2007-01-11',5,5,1000),
('18444447Y', 'Kora', 'Wich43210','2006-07-10',5,3,1000);

INSERT INTO TABLEE VALUES
('MESA45678B','BLACKJACK'),
('MESA45678A','ROULETTE');

INSERT INTO DEALER VALUES
('DEAL1234BB','Martín',1000),
('DEAL1234AA','Artiz',1000);

INSERT INTO PLAYED VALUES
('18449847Y','MESA45678B','2026-03-13',5000,'WIN'),
('18444447Y','MESA45678A','2026-03-13',3500,'LOSE');

INSERT INTO HAVE VALUES
('MESA45678B','DEAL1234BB'),
('MESA45678A','DEAL1234AA');

DELIMITER 
CREATE DEFINER=`root`@`localhost` PROCEDURE `add_dealers`(IN p_id_dealer VARCHAR(10), IN p_dealer_name VARCHAR(20), IN p_balance DECIMAL)
BEGIN

    INSERT INTO DEALER (
        ID_DEALER, DEALER_NAME, BALANCE
    )
    VALUES (
        p_id, p_name, p_balance
    );

END //

DELIMITER //

DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `add_users`(IN p_dni VARCHAR(10), IN p_username VARCHAR(20), IN p_password VARCHAR(10), IN p_birth DATE,IN p_times_played INT, IN p_maxcombo INT, IN p_balance DECIMAL(10,2))
BEGIN

    INSERT INTO USERS (
        DNI, USERNAME, PASWORD, DATE_OF_BIRTH, TIMES_PLAYED, MAX_COMBO, BALANCE
    )
    VALUES (
        p_dni, p_username, p_password, p_birth, p_times_played, p_maxcombo, p_balance
    );

END
DELIMITER ;

DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `register_game`(IN p_dni VARCHAR(10), IN p_table VARCHAR(10), IN p_date TIMESTAMP, IN p_bet INT, IN p_result VARCHAR(10) )
BEGIN

	INSERT INTO PLAYED (DNI, ID_TABLE,GAME_DATE, BET, RESULT)
    VALUES(p_dni, p_table, p_date, p_bet, p_result);
	
	UPDATE USERS
    SET TIMES_PLAYED = TIMES_PLAYED + 1
    WHERE DNI = p_dni;

	IF p_result = "WIN" THEN 
		UPDATE USERS
        SET BALANCE = BALANCE + p_bet
        WHERE DNI = p_dni;
	END IF;
END

DELIMITER ;

DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `assing_dealer_table`(IN p_table VARCHAR(10), IN p_dealer VARCHAR(10))
BEGIN
	
    INSERT INTO HAVE (ID_TABLE, ID_DEALER)
    VALUES (p_table, p_dealer);
    
END
DELIMITER ;